// List<Map> userList = [
//   {
//     "name": "Md. Emon Miah",
//     "profile_picture":
//     "https://images.pexels.com/photos/2182970/pexels-photo-2182970.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
//     "time": 6.15,
//     "last_message": "how are you?",
//     "isRead": false,
//     "message_count": 4,
//     "number" : "01456892142",
//     "incomming_call": true,
//     "status": true,
//   },
//   {
//     'name': 'Nuhan Bhai',
//     'profile_picture': 'https://buffer.com/cdn-cgi/image/w=7000,fit=contain,q=90,f=auto/library/content/images/2023/10/free-images.jpg',
//     'time': '10.15',
//     'last_message': 'Matis na?',
//     'isRead': true,
//     'message_count': '3',
//     'number' : '01456845142',
//     'incomming_call': false,
//     'status' : true,
//
//   },
//   {
//     'name': 'Kulsuma Akter',
//     'profile_picture':
//     'https://images.pexels.com/photos/2182970/pexels-photo-2182970.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
//     'time': '8.15',
//     'last_message': 'lath khaite?',
//     'isRead': false,
//     'message_count': '1',
//     'number' : "01454862142",
//     'incomming_call': true,
//     'status' : false,
//   },
//   {
//     'name': 'Md. Emon Miah',
//     'profile_picture':
//     'https://images.pexels.com/photos/2182970/pexels-photo-2182970.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
//     'time': '6.15',
//     'last_message': 'how are you?',
//     'isRead': false,
//     'message_count': '4',
//     'number' : '01456492142',
//     'incomming_call': true,
//     'status' : false,
//
//   },
//   {
//     'name': 'Nuhan Bhai',
//     'profile_picture': 'https://buffer.com/cdn-cgi/image/w=7000,fit=contain,q=90,f=auto/library/content/images/2023/10/free-images.jpg',
//     'time': '10.15',
//     'last_message': 'Matis na?',
//     'isRead': true,
//     'message_count': '3',
//     'number' : '01456876142',
//     'incomming_call': false,
//     'status' : false,
//
//   },
//   {
//     'name': 'Kulsuma Akter',
//     'profile_picture':
//     'https://images.pexels.com/photos/2182970/pexels-photo-2182970.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
//     'time': '8.15',
//     'last_message': 'lath khaite?',
//     'isRead': false,
//     'message_count': '1',
//     'number' : '01456893142',
//     'incomming_call': false,
//     'status' : false,
//
//   },
//   {
//     'name': 'Md. Siam Miah',
//     'profile_picture':
//     'https://images.pexels.com/photos/2182970/pexels-photo-2182970.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
//     'time': '6.15',
//     'last_message': 'how are you?',
//     'isRead': false,
//     'message_count': '4',
//     'number' : '01456893142',
//     'incomming_call': false,
//     'status' : false,
//
//   },
//   {
//     'name': 'Nuhan Bhai',
//     'profile_picture': 'https://buffer.com/cdn-cgi/image/w=7000,fit=contain,q=90,f=auto/library/content/images/2023/10/free-images.jpg',
//     'time': '10.15',
//     'last_message': 'Matis na?',
//     'isRead': true,
//     'message_count': '3',
//     'number' : '01456893142',
//     'incomming_call': true,
//     'status' : false,
//   },
//   {
//     'name': 'Siam Miah',
//     'profile_picture':
//     'https://images.pexels.com/photos/2182970/pexels-photo-2182970.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
//     'time': '8.15',
//     'last_message': 'lath khaite?',
//     'isRead': false,
//     'message_count': '1',
//     'number' : '01476892142',
//     'incomming_call': false,
//     'status' : false,
//   },
//   {
//     'name': 'Md. Emon Miah',
//     'profile_picture':
//     'https://images.pexels.com/photos/2182970/pexels-photo-2182970.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
//     'time': '6.15',
//     'last_message': 'how are you?',
//     'isRead': false,
//     'message_count': '4',
//     'number' : '01456891142',
//     'incomming_call': true,
//     'status' : false,
//   },
//   {
//     'name': 'Nuhan Bhai',
//     'profile_picture': 'https://buffer.com/cdn-cgi/image/w=7000,fit=contain,q=90,f=auto/library/content/images/2023/10/free-images.jpg',
//     'time': '10.15',
//     'last_message': 'Matis na?',
//     'isRead': true,
//     'message_count': '3',
//     'number' : '01456892142',
//     'incomming_call': true,
//     'status' : false,
//   },
//   {
//     'name': 'Kulsuma Akter',
//     'profile_picture':
//     'https://images.pexels.com/photos/2182970/pexels-photo-2182970.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
//     'time': '8.15',
//     'last_message': 'lath khaite?',
//     'isRead': false,
//     'message_count': '1',
//     'number' : '01456892142',
//     'incomming_call': true,
//     'status' : false,
//   },
//   {
//     'name': 'Md. Emon Miah',
//     'profile_picture':
//     'https://images.pexels.com/photos/2182970/pexels-photo-2182970.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
//     'time': '6.15',
//     'last_message': 'how are you?',
//     'isRead': false,
//     'message_count': '4',
//     'number' : '01456892142',
//     'incomming_call': false,
//     'status' : false,
//   },
//   {
//     'name': 'Nuhan Bhai',
//     'profile_picture': 'https://buffer.com/cdn-cgi/image/w=7000,fit=contain,q=90,f=auto/library/content/images/2023/10/free-images.jpg',
//     'time': '10.15',
//     'last_message': 'Matis na?',
//     'isRead': true,
//     'number' : '01456892142',
//     'incomming_call': false,
//     'status' : false,
//     'message_count': '3',
//   },
//   {
//     'name': 'Kulsuma Akter',
//     'profile_picture':
//     'https://images.pexels.com/photos/2182970/pexels-photo-2182970.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
//     'time': '8.15',
//     'last_message': 'lath khaite?',
//     'isRead': false,
//     'message_count': '1',
//     'number' : '01456892142',
//     'incomming_call': false,
//     'status' : false,
//   },
//   {
//     'name': 'Md. Emon Miah',
//     'profile_picture':
//     'https://images.pexels.com/photos/2182970/pexels-photo-2182970.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
//     'time': '6.15',
//     'last_message': 'how are you?',
//     'isRead': false,
//     'message_count': '4',
//     'number' : '01456892142',
//     'incomming_call': true,
//     'status' : false,
//   },
//   {
//     'name': 'Nuhan Bhai',
//     'profile_picture': 'https://buffer.com/cdn-cgi/image/w=7000,fit=contain,q=90,f=auto/library/content/images/2023/10/free-images.jpg',
//     'time': '10.15',
//     'last_message': 'Matis na?',
//     'isRead': true,
//     'number' : '01456892142',
//     'incomming_call': true,
//     'status' : false,
//     'message_count': '3',
//   },
//   {
//     'name': 'Kulsuma Akter',
//     'profile_picture':
//     'https://images.pexels.com/photos/2182970/pexels-photo-2182970.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
//     'time': '8.15',
//     'last_message': 'lath khaite?',
//     'isRead': false,
//     'message_count': '1',
//     'number' : '01456892142',
//     'incomming_call': false,
//     'status' : false,
//   },
//   {
//     'name': 'Md. Emon Miah',
//     'profile_picture':
//     'https://images.pexels.com/photos/2182970/pexels-photo-2182970.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
//     'time': '6.15',
//     'last_message': 'how are you?',
//     'isRead': false,
//     'message_count': '4',
//     'number' : '01456892142',
//     'incomming_call': true,
//     'status' : false,
//   },
// ];

import 'package:chat_app/Models/chats_user_model.dart';

List<ChatsUsers> chatusers = [
  ChatsUsers(
    name : 'Nuhan Bhai',
    profilePicture : 'https://buffer.com/cdn-cgi/image/w=7000,fit=contain,q=90,f=auto/library/content/images/2023/10/free-images.jpg',
    time : 10.15,
    lastMessage : 'Matis na?',
    isRead: true,
    messageCount: 3,
    number : '01456845142',
    incommingCall: false,
    status : true,
  )
];
